// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

package network

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BaseMessage_MessageType int32

const (
	BaseMessage_SendEvents BaseMessage_MessageType = 0
	BaseMessage_AddNode    BaseMessage_MessageType = 1
	BaseMessage_SyncEvents BaseMessage_MessageType = 2
)

var BaseMessage_MessageType_name = map[int32]string{
	0: "SendEvents",
	1: "AddNode",
	2: "SyncEvents",
}

var BaseMessage_MessageType_value = map[string]int32{
	"SendEvents": 0,
	"AddNode":    1,
	"SyncEvents": 2,
}

func (x BaseMessage_MessageType) String() string {
	return proto.EnumName(BaseMessage_MessageType_name, int32(x))
}

func (BaseMessage_MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{0, 0}
}

type BaseMessage struct {
	OwnerId              string                     `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Hash                 string                     `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	TimeStamp            *timestamp.Timestamp       `protobuf:"bytes,3,opt,name=time_stamp,json=timeStamp,proto3" json:"time_stamp,omitempty"`
	Type                 BaseMessage_MessageType    `protobuf:"varint,4,opt,name=type,proto3,enum=messages.BaseMessage_MessageType" json:"type,omitempty"`
	Transactions         []*BaseMessage_Transaction `protobuf:"bytes,5,rep,name=transactions,proto3" json:"transactions,omitempty"`
	SendEventMessage     *SendEventMessage          `protobuf:"bytes,6,opt,name=send_event_message,json=sendEventMessage,proto3" json:"send_event_message,omitempty"`
	CommandMessage       *CommandMessage            `protobuf:"bytes,7,opt,name=command_message,json=commandMessage,proto3" json:"command_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *BaseMessage) Reset()         { *m = BaseMessage{} }
func (m *BaseMessage) String() string { return proto.CompactTextString(m) }
func (*BaseMessage) ProtoMessage()    {}
func (*BaseMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{0}
}

func (m *BaseMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseMessage.Unmarshal(m, b)
}
func (m *BaseMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseMessage.Marshal(b, m, deterministic)
}
func (m *BaseMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseMessage.Merge(m, src)
}
func (m *BaseMessage) XXX_Size() int {
	return xxx_messageInfo_BaseMessage.Size(m)
}
func (m *BaseMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseMessage.DiscardUnknown(m)
}

var xxx_messageInfo_BaseMessage proto.InternalMessageInfo

func (m *BaseMessage) GetOwnerId() string {
	if m != nil {
		return m.OwnerId
	}
	return ""
}

func (m *BaseMessage) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *BaseMessage) GetTimeStamp() *timestamp.Timestamp {
	if m != nil {
		return m.TimeStamp
	}
	return nil
}

func (m *BaseMessage) GetType() BaseMessage_MessageType {
	if m != nil {
		return m.Type
	}
	return BaseMessage_SendEvents
}

func (m *BaseMessage) GetTransactions() []*BaseMessage_Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func (m *BaseMessage) GetSendEventMessage() *SendEventMessage {
	if m != nil {
		return m.SendEventMessage
	}
	return nil
}

func (m *BaseMessage) GetCommandMessage() *CommandMessage {
	if m != nil {
		return m.CommandMessage
	}
	return nil
}

type BaseMessage_Transaction struct {
	OwnerId              string   `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Hash                 string   `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	InAccount            string   `protobuf:"bytes,3,opt,name=in_account,json=inAccount,proto3" json:"in_account,omitempty"`
	OutAccount           string   `protobuf:"bytes,4,opt,name=out_account,json=outAccount,proto3" json:"out_account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseMessage_Transaction) Reset()         { *m = BaseMessage_Transaction{} }
func (m *BaseMessage_Transaction) String() string { return proto.CompactTextString(m) }
func (*BaseMessage_Transaction) ProtoMessage()    {}
func (*BaseMessage_Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{0, 0}
}

func (m *BaseMessage_Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseMessage_Transaction.Unmarshal(m, b)
}
func (m *BaseMessage_Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseMessage_Transaction.Marshal(b, m, deterministic)
}
func (m *BaseMessage_Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseMessage_Transaction.Merge(m, src)
}
func (m *BaseMessage_Transaction) XXX_Size() int {
	return xxx_messageInfo_BaseMessage_Transaction.Size(m)
}
func (m *BaseMessage_Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseMessage_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_BaseMessage_Transaction proto.InternalMessageInfo

func (m *BaseMessage_Transaction) GetOwnerId() string {
	if m != nil {
		return m.OwnerId
	}
	return ""
}

func (m *BaseMessage_Transaction) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *BaseMessage_Transaction) GetInAccount() string {
	if m != nil {
		return m.InAccount
	}
	return ""
}

func (m *BaseMessage_Transaction) GetOutAccount() string {
	if m != nil {
		return m.OutAccount
	}
	return ""
}

type SendEventMessage struct {
	EventId              string   `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendEventMessage) Reset()         { *m = SendEventMessage{} }
func (m *SendEventMessage) String() string { return proto.CompactTextString(m) }
func (*SendEventMessage) ProtoMessage()    {}
func (*SendEventMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{1}
}

func (m *SendEventMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendEventMessage.Unmarshal(m, b)
}
func (m *SendEventMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendEventMessage.Marshal(b, m, deterministic)
}
func (m *SendEventMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendEventMessage.Merge(m, src)
}
func (m *SendEventMessage) XXX_Size() int {
	return xxx_messageInfo_SendEventMessage.Size(m)
}
func (m *SendEventMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SendEventMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SendEventMessage proto.InternalMessageInfo

func (m *SendEventMessage) GetEventId() string {
	if m != nil {
		return m.EventId
	}
	return ""
}

type CommandMessage struct {
	CommandId            string   `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommandMessage) Reset()         { *m = CommandMessage{} }
func (m *CommandMessage) String() string { return proto.CompactTextString(m) }
func (*CommandMessage) ProtoMessage()    {}
func (*CommandMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{2}
}

func (m *CommandMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandMessage.Unmarshal(m, b)
}
func (m *CommandMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandMessage.Marshal(b, m, deterministic)
}
func (m *CommandMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandMessage.Merge(m, src)
}
func (m *CommandMessage) XXX_Size() int {
	return xxx_messageInfo_CommandMessage.Size(m)
}
func (m *CommandMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandMessage.DiscardUnknown(m)
}

var xxx_messageInfo_CommandMessage proto.InternalMessageInfo

func (m *CommandMessage) GetCommandId() string {
	if m != nil {
		return m.CommandId
	}
	return ""
}

func init() {
	proto.RegisterEnum("messages.BaseMessage_MessageType", BaseMessage_MessageType_name, BaseMessage_MessageType_value)
	proto.RegisterType((*BaseMessage)(nil), "messages.BaseMessage")
	proto.RegisterType((*BaseMessage_Transaction)(nil), "messages.BaseMessage.Transaction")
	proto.RegisterType((*SendEventMessage)(nil), "messages.SendEventMessage")
	proto.RegisterType((*CommandMessage)(nil), "messages.CommandMessage")
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor_4dc296cbfe5ffcd5) }

var fileDescriptor_4dc296cbfe5ffcd5 = []byte{
	// 389 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x4d, 0x6f, 0xa3, 0x30,
	0x10, 0x5d, 0x12, 0x36, 0x09, 0xc3, 0x8a, 0x45, 0x3e, 0xb1, 0x91, 0x56, 0xa5, 0x5c, 0xca, 0xa5,
	0x20, 0xa5, 0xea, 0xa1, 0xbd, 0xa5, 0x55, 0xa4, 0xe6, 0xd0, 0x1e, 0x48, 0xee, 0xc8, 0xc1, 0x6e,
	0x82, 0x14, 0x6c, 0x14, 0x9b, 0x56, 0x91, 0xfa, 0xd3, 0xfa, 0xe3, 0x2a, 0x8c, 0x21, 0x1f, 0x52,
	0x0f, 0x3d, 0xe1, 0x99, 0x79, 0xef, 0xf9, 0xcd, 0x33, 0xe0, 0x14, 0x54, 0x08, 0xbc, 0xa6, 0x22,
	0x2a, 0x77, 0x5c, 0x72, 0x34, 0x6a, 0xeb, 0xf1, 0x55, 0xce, 0xb2, 0x6d, 0x45, 0x68, 0xbc, 0xe6,
	0x7c, 0xbd, 0xa5, 0xb1, 0x9a, 0xaf, 0xaa, 0xd7, 0x58, 0xe6, 0x05, 0x15, 0x12, 0x17, 0x65, 0x43,
	0x09, 0x3e, 0x4d, 0xb0, 0x1f, 0xb0, 0xa0, 0xcf, 0x0d, 0x13, 0xfd, 0x83, 0x11, 0x7f, 0x67, 0x74,
	0x97, 0xe6, 0xc4, 0x33, 0x7c, 0x23, 0xb4, 0x92, 0xa1, 0xaa, 0xe7, 0x04, 0x21, 0x30, 0x37, 0x58,
	0x6c, 0xbc, 0x9e, 0x6a, 0xab, 0x33, 0xba, 0x03, 0xa8, 0x15, 0x53, 0x25, 0xe9, 0xf5, 0x7d, 0x23,
	0xb4, 0x27, 0xe3, 0xa8, 0xb9, 0x34, 0x6a, 0x2f, 0x8d, 0x96, 0xed, 0xa5, 0x89, 0x55, 0xa3, 0x17,
	0xf5, 0x11, 0xdd, 0x82, 0x29, 0xf7, 0x25, 0xf5, 0x4c, 0xdf, 0x08, 0x9d, 0xc9, 0x65, 0xd4, 0xed,
	0x72, 0x64, 0x27, 0xd2, 0xdf, 0xe5, 0xbe, 0xa4, 0x89, 0x82, 0xa3, 0x19, 0xfc, 0x91, 0x3b, 0xcc,
	0x04, 0xce, 0x64, 0xce, 0x99, 0xf0, 0x7e, 0xfb, 0xfd, 0xd0, 0xfe, 0x8e, 0xbe, 0x3c, 0x20, 0x93,
	0x13, 0x1a, 0x7a, 0x02, 0x24, 0x28, 0x23, 0x29, 0x7d, 0xa3, 0x4c, 0xa6, 0x9a, 0xec, 0x0d, 0xf4,
	0x02, 0x9d, 0xd8, 0x82, 0x32, 0x32, 0xab, 0x21, 0x5a, 0x31, 0x71, 0xc5, 0x59, 0x07, 0x4d, 0xe1,
	0x6f, 0xc6, 0x8b, 0x02, 0x33, 0xd2, 0xc9, 0x0c, 0x95, 0x8c, 0x77, 0x90, 0x79, 0x6c, 0x00, 0xad,
	0x88, 0x93, 0x9d, 0xd4, 0xe3, 0x0f, 0xb0, 0x8f, 0x9c, 0xfe, 0xf4, 0x0d, 0xfe, 0x03, 0xe4, 0x2c,
	0xc5, 0x59, 0xc6, 0x2b, 0x26, 0xd5, 0x1b, 0x58, 0x89, 0x95, 0xb3, 0x69, 0xd3, 0x40, 0x17, 0x60,
	0xf3, 0x4a, 0x76, 0x73, 0x53, 0xcd, 0x81, 0x57, 0x52, 0x03, 0x82, 0x7b, 0xb0, 0x8f, 0x62, 0x46,
	0x0e, 0x40, 0xb7, 0xb5, 0x70, 0x7f, 0x21, 0x1b, 0x86, 0x53, 0x42, 0x5e, 0x38, 0xa1, 0xae, 0xa1,
	0x86, 0x7b, 0x96, 0xe9, 0x61, 0x2f, 0xb8, 0x06, 0xf7, 0x3c, 0xa2, 0xda, 0x7e, 0x93, 0xea, 0xc1,
	0xbe, 0xaa, 0xe7, 0x24, 0x88, 0xc1, 0x39, 0x8d, 0xa2, 0x36, 0xdf, 0xa6, 0xd7, 0xc1, 0x2d, 0xdd,
	0x99, 0x93, 0xd5, 0x40, 0xfd, 0x43, 0x37, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xa0, 0xe9, 0x19,
	0x86, 0xea, 0x02, 0x00, 0x00,
}
